# Generated by Django 4.0.2 on 2022-02-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id_destination', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_column='city', max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('switch', models.SmallIntegerField(blank=True, default='1', null=True)),
                ('hotel', models.CharField(max_length=50, unique=True)),
                ('hotel_address', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
