# Generated by Django 4.0.2 on 2022-02-20 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id_trip', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('adult_number', models.CharField(blank=True, max_length=50, null=True)),
                ('children_number', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=252, verbose_name='Note')),
                ('trip_plan_date', models.DateField(blank=True, null=True, verbose_name='trip date')),
                ('payment_method', models.CharField(choices=[('Cache', 'Cache'), ('Installments', 'Installments')], default='Cache', max_length=30, verbose_name='Payment method')),
                ('custome_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fligh_to_city_hotel', models.ForeignKey(db_column='id_destination_to', on_delete=django.db.models.deletion.CASCADE, related_name='to_city_hotel', to='destination.destination')),
                ('flight_from_city', models.ForeignKey(db_column='id_destination_from', on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='destination.destination')),
            ],
        ),
    ]
